### ISSUE TITLE
[Bug]: Missing loaded files

### ISSUE THREAD

**Issue by Chrico** [inpsyde/vip-composer-plugin#10]
### Description of the bug

It looks like that https://github.com/Automattic/vip-go-mu-plugins/blob/develop/000-pre-vip-config/requires.php needs to be loaded locally in wp-config.php or relatively early. Currently our `vip-composer-plugin` does not take that file into consideration and WP VIP does just leave a comment in the file 🤔 

> You should make sure to include this file locally in case you're not using VIP Local Development Environment

We should add this file (and others...?) to our `vip-composer-plugin` as files which should be required in `wp-config.php`.

### Reproduction instructions

1. Create a `mu-plugin`
2. do a  `class_exists(VIP_Request_Block::class)`
3. it will return `false` because its not autoloaded and the "manual" `require_once`-file is not added by us.

### Expected behavior

Add the `/vip-go-mu-plugins/000-pre-vip-config/requires.php` to `wp-config.php`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gmazzap** [comment]
Done in #18
